version: '3'

services:

    malexer-twemproxy:
        build:
            context: .
            dockerfile: Dockerfile
        image: malexer/twemproxy:0.5.0
        container_name: malexer-twemproxy
        environment:
            REDIS_SERVERS: "127.0.1.1:6379:1,127.0.1.2:6379:1,127.0.1.3:6379:1"
        ports:
            - 6380:6380
